### ISSUE TITLE
Contac you

### ISSUE THREAD

**Issue by tutanota** [AlvinKuruvilla/Code-Brew#1]
I need to contact you to ask you something about a previous project you did

**Comment by AlvinKuruvilla** [comment]
What project is that ?

**Comment by tutanota** [comment]
this problem:
I have created dns records and it has been around 24 hours and I think the dns has propagated and I am getting this issue:
acme: Error -> One or more domains had a problem:
[www.linkedin.alvin-testbed.club] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: SERVFAIL looking up A for www.linkedin.alvin-testbed.club, url:


How did you solve that problem because I saw that they deleted the post they made of your question

**Comment by AlvinKuruvilla** [comment]
Very sorry for the late response
This could likely due to the name server not being pointed to the IP that is running Evilginx
